require('dotenv').config();
const express=require('express'), cors=require('cors'), helmet=require('helmet'), rateLimit=require('express-rate-limit'), axios=require('axios'), http=require('http'), {Server}=require('socket.io'), multer=require('multer');
const {v4:uuid}=require('uuid');
let admin=null;
try{
  const firebaseAdmin=require('firebase-admin');
  if(process.env.FIREBASE_SERVICE_ACCOUNT_JSON?.trim().startsWith('{')) admin=firebaseAdmin.initializeApp({credential:firebaseAdmin.credential.cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON))});
  else if(process.env.FIREBASE_PROJECT_ID && !process.env.FIREBASE_PROJECT_ID.includes('PASTE')) admin=firebaseAdmin.initializeApp({credential:firebaseAdmin.credential.cert({projectId:process.env.FIREBASE_PROJECT_ID,clientEmail:process.env.FIREBASE_CLIENT_EMAIL,privateKey:process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g,'\n')})});
}catch(e){ console.log('Firebase Admin not ready:',e.message); }

const db={
 users:[{id:'user_manan',firebaseUid:'demo_manan_uid',name:'Manan Patel',email:'manan@ridelink.com',phone:'0400000001',role:'passenger',trustRating:4.90,verificationStatus:'phone_verified',driverBadge:false,savedRoutes:['Landsdale → Curtin','Curtin → Joondalup']},{id:'user_kasper',firebaseUid:'demo_kasper_uid',name:'Kasper Li',email:'kasper@ridelink.com',phone:'0400000002',role:'driver',trustRating:4.98,verificationStatus:'verified_driver',driverBadge:true,vehicle:{model:'Toyota Corolla',plate:'1ABC234',seats:3}}],
 trips:[{id:'trip_001',driverId:'user_kasper',startLocation:'Landsdale',destination:'Curtin University',departureTime:'2026-09-17T08:00:00',availableSeats:3,confirmedSeatCount:0,costPerSeat:7,status:'published',communityId:'community_curtin',pickupSuggestion:'Shell Station, Landsdale',dropoffPlan:'Landsdale → Curtin University'},{id:'trip_002',driverId:'user_kasper',startLocation:'Landsdale',destination:'Curtin University',departureTime:'2026-09-17T08:15:00',availableSeats:2,confirmedSeatCount:0,costPerSeat:8,status:'published',communityId:'community_curtin',pickupSuggestion:'Shell Station, Landsdale',dropoffPlan:'Landsdale → Curtin University'}],
 rideRequests:[],
 bookings:[{id:'booking_demo_confirmed',tripId:'trip_001',passengerId:'user_manan',pickupLocation:'Shell Station, Landsdale',dropoffLocation:'Curtin University',seatsNeeded:2,extraPassengerNote:'Manan + 1 passenger',status:'confirmed',totalCost:14,createdAt:new Date().toISOString()}],
 communities:[{id:'community_curtin',name:'Curtin Students',route:'Landsdale → Curtin University',startArea:'Landsdale',destination:'Curtin University',commonTime:'7:30 AM - 9:00 AM',days:'Monday to Friday',passengers:12,drivers:4,nextRideTripId:'trip_001',createdByAi:true},{id:'community_fifo',name:'FIFO Workers',route:'Northern Suburbs → Perth Airport',startArea:'Northern Suburbs',destination:'Perth Airport',commonTime:'Early morning',days:'Roster based',passengers:18,drivers:5,nextRideTripId:null,createdByAi:true},{id:'community_optus',name:'Optus Stadium Events',route:'Optus Stadium → North Suburbs',startArea:'Optus Stadium',destination:'North Suburbs',commonTime:'After events',days:'Event days',passengers:31,drivers:8,nextRideTripId:null,createdByAi:true}],
 messages:[], ratings:[], incidents:[], documents:[]
};
const userById=id=>db.users.find(u=>u.id===id); const safe=u=>({...u});
async function auth(req,res,next){
 const h=req.headers.authorization||'', token=h.startsWith('Bearer ')?h.slice(7):null;
 if(!token){ if(process.env.DEV_ALLOW_NO_AUTH==='true'){req.user=db.users[0];return next()} return res.status(401).json({error:'Firebase ID token required'}); }
 try{ if(!admin) throw new Error('Firebase Admin not configured'); const decoded=await require('firebase-admin').auth().verifyIdToken(token); let u=db.users.find(x=>x.firebaseUid===decoded.uid); if(!u){u={id:uuid(),firebaseUid:decoded.uid,name:decoded.name||decoded.email?.split('@')[0]||'RideLink User',email:decoded.email||decoded.uid+'@firebase.local',phone:decoded.phone_number||'',role:'passenger',trustRating:4.70,verificationStatus:'firebase_verified',driverBadge:false,savedRoutes:[]}; db.users.push(u)} req.user=u; req.firebaseUser=decoded; next(); }
 catch(e){res.status(401).json({error:'Invalid Firebase token',details:e.message})}
}
function hasMapbox(){return !!(process.env.MAPBOX_ACCESS_TOKEN && !process.env.MAPBOX_ACCESS_TOKEN.includes('PASTE'))}
function demoCoord(q){q=(q||'').toLowerCase(); if(q.includes('landsdale'))return{placeName:'Landsdale WA',lat:-31.8070,lng:115.8620}; if(q.includes('curtin'))return{placeName:'Curtin University WA',lat:-32.0062,lng:115.8941}; if(q.includes('airport'))return{placeName:'Perth Airport WA',lat:-31.9403,lng:115.9669}; return{placeName:q,lat:-31.9505,lng:115.8605}}
async function geocode(q){ if(!hasMapbox()) return {...demoCoord(q),source:'demo'}; const r=await axios.get('https://api.mapbox.com/search/geocode/v6/forward',{params:{q,access_token:process.env.MAPBOX_ACCESS_TOKEN,country:process.env.MAPBOX_COUNTRY||'AU',limit:1,proximity:process.env.MAPBOX_DEFAULT_PROXIMITY||'115.8575,-31.9505'}}); const f=r.data.features?.[0]; if(!f) throw new Error('No geocode result'); const [lng,lat]=f.geometry.coordinates; return{placeName:f.properties?.full_address||f.properties?.name||q,lat,lng,source:'mapbox'} }
async function route(start,dest){ const a=typeof start==='string'?await geocode(start):start, b=typeof dest==='string'?await geocode(dest):dest; if(!hasMapbox()) return{origin:a,destination:b,distanceKm:17.4,durationMinutes:28,geometry:null,source:'demo'}; const coords=`${a.lng},${a.lat};${b.lng},${b.lat}`; const r=await axios.get(`https://api.mapbox.com/directions/v5/mapbox/driving/${coords}`,{params:{access_token:process.env.MAPBOX_ACCESS_TOKEN,geometries:'geojson',overview:'full',steps:true}}); const rt=r.data.routes?.[0]; return{origin:a,destination:b,distanceKm:+(rt.distance/1000).toFixed(2),durationMinutes:Math.round(rt.duration/60),geometry:rt.geometry,source:'mapbox'} }
async function matches(reqObj){
 const out=[]; for(const t of db.trips){ if(t.status!=='published')continue; const seats=t.availableSeats-t.confirmedSeatCount; if(seats<reqObj.seatsNeeded)continue; const driver=userById(t.driverId); const dest=t.destination.toLowerCase().includes(reqObj.destination.toLowerCase())||reqObj.destination.toLowerCase().includes(t.destination.toLowerCase()); const pick=t.startLocation.toLowerCase().includes(reqObj.pickupLocation.toLowerCase())||reqObj.pickupLocation.toLowerCase().includes(t.startLocation.toLowerCase()); let rt; try{rt=await route(reqObj.pickupLocation,reqObj.destination)}catch(e){rt={distanceKm:17.4,durationMinutes:28,geometry:null,source:'fallback'}} const detour=pick?4:7; const score=Math.min(99,(dest?40:25)+(pick?15:8)+20+Math.round((driver.trustRating/5)*15)+(detour<=5?10:7)); out.push({tripId:t.id,driverId:t.driverId,driverName:driver.name,trustRating:driver.trustRating,driverBadge:driver.driverBadge,vehicle:driver.vehicle,startLocation:t.startLocation,destination:t.destination,departureTime:t.departureTime,seatsAvailable:seats,seatsNeeded:reqObj.seatsNeeded,extraPassengerNote:reqObj.extraPassengerNote,matchPercentage:score,detourMinutes:detour,pickupSuggestion:t.pickupSuggestion,dropoffPlan:t.dropoffPlan,costEach:t.costPerSeat,totalCost:t.costPerSeat*reqObj.seatsNeeded,route:rt}) }
 return out.sort((a,b)=>b.matchPercentage-a.matchPercentage)
}
const app=express(), upload=multer({dest:'uploads/'}); app.use(helmet()); app.use(cors({origin:process.env.CLIENT_URL==='*'?'*':process.env.CLIENT_URL||'*'})); app.use(express.json({limit:'5mb'})); app.use(rateLimit({windowMs:15*60*1000,max:300}));
app.get('/',(_,res)=>res.json({app:'RideLink API',status:'running'})); app.get('/api/v1/health',(_,res)=>res.json({status:'ok',firebaseAdmin:!!admin,devNoAuth:process.env.DEV_ALLOW_NO_AUTH==='true',mapboxConfigured:hasMapbox(),message:'RideLink backend working'}));
app.post('/api/v1/auth/demo-login',(req,res)=>{const u=db.users.find(x=>x.email===(req.body.email||'manan@ridelink.com'))||db.users[0];res.json({message:'Demo login successful',user:safe(u),demoMode:true})});
app.post('/api/v1/auth/firebase-login',auth,(req,res)=>res.json({message:'Firebase login verified',user:safe(req.user)}));
app.post('/api/v1/auth/register-profile',auth,(req,res)=>{Object.assign(req.user,{name:req.body.name||req.user.name,phone:req.body.phone||req.user.phone,role:req.body.role||req.user.role});res.status(201).json({message:'Profile synced',user:safe(req.user)})});
app.post('/api/v1/auth/verify-otp',(req,res)=>res.json({message:'OTP verified',verified:true}));
app.get('/api/v1/users/me',auth,(req,res)=>res.json({user:safe(req.user)})); app.patch('/api/v1/users/me',auth,(req,res)=>{Object.assign(req.user,req.body);res.json({message:'Profile updated',user:safe(req.user)})});
app.post('/api/v1/verification/documents',auth,upload.any(),(req,res)=>{db.documents.push({id:uuid(),userId:req.user.id,status:'submitted',files:req.files?.length||0}); req.user.role='driver'; req.user.verificationStatus='driver_verification_submitted'; res.status(201).json({message:'Driver verification submitted',driverBadge:false})});
app.post('/api/v1/verification/demo-approve-driver',auth,(req,res)=>{Object.assign(req.user,{role:'driver',verificationStatus:'verified_driver',driverBadge:true,vehicle:{model:'Toyota Corolla',plate:'1ABC234',seats:3}});res.json({message:'Driver approved',user:safe(req.user)})});
app.post('/api/v1/trips',auth,async(req,res)=>{const t={id:uuid(),driverId:req.user.id,startLocation:req.body.startLocation,destination:req.body.destination,departureTime:req.body.departureTime,availableSeats:+req.body.availableSeats,costPerSeat:+req.body.costPerSeat,confirmedSeatCount:0,status:'published',communityId:req.body.communityId||null,pickupSuggestion:`Shell Station, ${req.body.startLocation}`,dropoffPlan:`${req.body.startLocation} → ${req.body.destination}`,createdAt:new Date().toISOString()}; try{t.route=await route(t.startLocation,t.destination)}catch(e){t.route={source:'fallback',error:e.message}} db.trips.push(t); res.status(201).json({message:'Trip published',trip:t})});
app.get('/api/v1/trips/mine',auth,(req,res)=>res.json({trips:db.trips.filter(t=>t.driverId===req.user.id)})); app.get('/api/v1/trips/:id',(req,res)=>{const t=db.trips.find(x=>x.id===req.params.id); if(!t)return res.status(404).json({error:'Trip not found'}); res.json({trip:t,driver:safe(userById(t.driverId)||{})})});
app.get('/api/v1/trips/:id/plan',(req,res)=>{const t=db.trips.find(x=>x.id===req.params.id)||db.trips[0]; const bs=db.bookings.filter(b=>b.tripId===t.id&&['pending','confirmed'].includes(b.status)); res.json({tripId:t.id,start:t.startLocation,stops:bs.length?bs.map(b=>({type:'pickup',passenger:b.extraPassengerNote,location:b.pickupLocation,seats:b.seatsNeeded})):[{type:'pickup',passenger:'Manan + 1 passenger',location:'Shell Station, Landsdale',seats:2}],final:t.destination,seatsUsed:`${bs.reduce((s,b)=>s+b.seatsNeeded,0)||2}/${t.availableSeats}`,extraTime:'+4 min',smartPickup:t.pickupSuggestion,smartDropoff:t.dropoffPlan,route:t.route||null})});
app.post('/api/v1/ride-requests',auth,async(req,res)=>{const r={id:uuid(),passengerId:req.user.id,pickupLocation:req.body.pickupLocation,destination:req.body.destination,preferredTime:req.body.preferredTime,flexibilityMinutes:+(req.body.flexibilityMinutes||15),seatsNeeded:+(req.body.seatsNeeded||1),extraPassengerNote:req.body.extraPassengerNote||'',status:'searching',createdAt:new Date().toISOString()}; db.rideRequests.push(r); res.status(201).json({message:'Ride request created',request:r,matches:await matches(r)})});
app.get('/api/v1/ride-requests/:id/matches',async(req,res)=>{const r=db.rideRequests.find(x=>x.id===req.params.id)||{id:'demo_request',pickupLocation:'Landsdale',destination:'Curtin University',preferredTime:'2026-09-17T08:00:00',seatsNeeded:2,extraPassengerNote:'Manan + 1 passenger'};res.json({request:r,matches:await matches(r)})});
app.post('/api/v1/bookings',auth,(req,res)=>{const t=db.trips.find(x=>x.id===req.body.tripId); if(!t)return res.status(404).json({error:'Trip not found'}); const left=t.availableSeats-t.confirmedSeatCount; if(+req.body.seatsNeeded>left)return res.status(400).json({error:'Not enough seats available',seatsLeft:left}); const b={id:uuid(),tripId:t.id,passengerId:req.user.id,pickupLocation:req.body.pickupLocation,dropoffLocation:req.body.dropoffLocation,seatsNeeded:+req.body.seatsNeeded,extraPassengerNote:req.body.extraPassengerNote,status:'pending',totalCost:+req.body.seatsNeeded*t.costPerSeat,createdAt:new Date().toISOString()}; db.bookings.push(b); res.status(201).json({message:'Request sent. Waiting for driver approval.',booking:b})});
app.get('/api/v1/bookings/mine',auth,(req,res)=>res.json({bookings:db.bookings.filter(b=>b.passengerId===req.user.id)})); app.get('/api/v1/bookings/driver/requests',auth,(req,res)=>{const tripIds=db.trips.filter(t=>t.driverId===req.user.id||process.env.DEV_ALLOW_NO_AUTH==='true').map(t=>t.id);res.json({requests:db.bookings.filter(b=>tripIds.includes(b.tripId)).map(b=>({...b,passenger:safe(userById(b.passengerId)||{}),trip:db.trips.find(t=>t.id===b.tripId)}))})});
app.patch('/api/v1/bookings/:id',auth,(req,res)=>{const b=db.bookings.find(x=>x.id===req.params.id); if(!b)return res.status(404).json({error:'Booking not found'}); const old=b.status; b.status=req.body.status; b.updatedAt=new Date().toISOString(); if(old!=='confirmed'&&b.status==='confirmed'){const t=db.trips.find(x=>x.id===b.tripId); if(t)t.confirmedSeatCount+=b.seatsNeeded} res.json({message:`Booking ${b.status}`,booking:b})});
app.get('/api/v1/communities',(req,res)=>res.json({communities:db.communities})); app.get('/api/v1/communities/:id',(req,res)=>{const c=db.communities.find(x=>x.id===req.params.id); if(!c)return res.status(404).json({error:'Community not found'}); res.json({community:c,nextRide:db.trips.find(t=>t.id===c.nextRideTripId)||null})});
app.post('/api/v1/communities/:id/join',auth,(req,res)=>res.json({message:'Joined community',community:db.communities.find(c=>c.id===req.params.id)}));
app.get('/api/v1/communities/:id/matches',auth,async(req,res)=>{const c=db.communities.find(x=>x.id===req.params.id)||db.communities[0]; const r={pickupLocation:c.startArea,destination:c.destination,preferredTime:'2026-09-17T08:00:00',seatsNeeded:+(req.query.seatsNeeded||2),extraPassengerNote:'Manan + 1 passenger'}; res.json({community:c,request:r,matches:await matches(r)})});
app.post('/api/v1/communities/:id/trips',auth,(req,res)=>{const c=db.communities.find(x=>x.id===req.params.id)||db.communities[0]; const t={id:uuid(),driverId:req.user.id,startLocation:req.body.startLocation||c.startArea,destination:req.body.destination||c.destination,departureTime:req.body.departureTime||'2026-09-17T08:00:00',availableSeats:+(req.body.availableSeats||3),costPerSeat:+(req.body.costPerSeat||7),confirmedSeatCount:0,status:'published',communityId:c.id,pickupSuggestion:`Shell Station, ${c.startArea}`,dropoffPlan:`${c.startArea} → ${c.destination}`}; db.trips.push(t); c.nextRideTripId=t.id; res.status(201).json({message:'Community ride published',trip:t})});
app.get('/api/v1/communities/:id/driver-matches',auth,(req,res)=>res.json({message:'AI found passengers near your route',passengers:[{name:'Manan + 1',pickup:'Landsdale',seatsNeeded:2,trustRating:4.90},{name:'Khushi',pickup:'Mirrabooka',seatsNeeded:1,trustRating:4.85}],suggestedPickup:'Shell Station, Landsdale',totalDetour:'+7 min',seatsUsed:'3/3'}));
app.post('/api/v1/messages',auth,(req,res)=>{const m={id:uuid(),tripId:req.body.tripId,senderId:req.user.id,message:req.body.message,sentAt:new Date().toISOString()}; db.messages.push(m); res.status(201).json({message:'Message sent',data:m})}); app.get('/api/v1/messages/:tripId',(req,res)=>res.json({messages:db.messages.filter(m=>m.tripId===req.params.tripId).length?db.messages.filter(m=>m.tripId===req.params.tripId):[{sender:'Driver',message:'I will arrive in 5 minutes.'},{sender:'You',message:'Okay, I am with my brother at Shell Station.'}]}));
app.post('/api/v1/ratings',auth,(req,res)=>{const overall=((+req.body.safety||5)+(+req.body.onTime||5)+(+req.body.communication||5))/3; const r={id:uuid(),...req.body,fromUserId:req.user.id,overall:+overall.toFixed(2),createdAt:new Date().toISOString()}; db.ratings.push(r); res.status(201).json({message:'Rating submitted',rating:r})});
app.post('/api/v1/safety/sos',auth,(req,res)=>res.status(201).json({message:'SOS triggered. Emergency contacts notified.',tripId:req.body.tripId,userId:req.user.id,location:{lat:req.body.lat,lng:req.body.lng},triggeredAt:new Date().toISOString()}));
app.post('/api/v1/safety/incidents',auth,(req,res)=>{const i={id:uuid(),...req.body,userId:req.user.id,status:'open',createdAt:new Date().toISOString()}; db.incidents.push(i); res.status(201).json({message:'Safety incident reported',incident:i})});
app.get('/api/v1/mapbox/geocode',async(req,res,next)=>{try{res.json({result:await geocode(req.query.q),mapboxConfigured:hasMapbox()})}catch(e){next(e)}}); app.get('/api/v1/mapbox/route',async(req,res,next)=>{try{res.json({result:await route(req.query.start,req.query.destination),mapboxConfigured:hasMapbox()})}catch(e){next(e)}});
app.use((req,res)=>res.status(404).json({error:'Route not found',path:req.originalUrl})); app.use((err,req,res,next)=>res.status(500).json({error:err.message}));
const server=http.createServer(app); const io=new Server(server,{cors:{origin:process.env.CLIENT_URL==='*'?'*':process.env.CLIENT_URL||'*'}}); io.on('connection',socket=>{socket.on('join_trip',d=>socket.join('trip:'+d.tripId)); socket.on('driver_location_update',d=>io.to('trip:'+d.tripId).emit('driver_location_update',{...d,updatedAt:new Date().toISOString()})); socket.on('send_message',d=>io.to('trip:'+d.tripId).emit('new_message',{...d,sentAt:new Date().toISOString()}));});
server.listen(process.env.PORT||5000,()=>console.log('RideLink backend running on http://localhost:'+(process.env.PORT||5000)));
