CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE users(id UUID PRIMARY KEY, firebase_uid TEXT UNIQUE, name TEXT, email TEXT UNIQUE, phone TEXT, role TEXT, trust_rating NUMERIC(3,2), verification_status TEXT, driver_badge BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE trips(id UUID PRIMARY KEY, driver_id UUID, start_location_name TEXT, destination_name TEXT, start_geo GEOGRAPHY(Point,4326), destination_geo GEOGRAPHY(Point,4326), departure_time TIMESTAMP, available_seats INT, confirmed_seat_count INT DEFAULT 0, cost_per_seat NUMERIC(10,2), status TEXT DEFAULT 'published', community_id UUID, route_geometry JSONB, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ride_requests(id UUID PRIMARY KEY, passenger_id UUID, pickup_location_name TEXT, destination_name TEXT, pickup_geo GEOGRAPHY(Point,4326), destination_geo GEOGRAPHY(Point,4326), preferred_time TIMESTAMP, flexibility_minutes INT, seats_needed INT, extra_passenger_note TEXT, status TEXT DEFAULT 'searching', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE bookings(id UUID PRIMARY KEY, trip_id UUID, passenger_id UUID, pickup_location_name TEXT, dropoff_location_name TEXT, seats_needed INT, extra_passenger_note TEXT, total_cost NUMERIC(10,2), status TEXT DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE communities(id UUID PRIMARY KEY, name TEXT, route TEXT, start_area TEXT, destination TEXT, common_time TEXT, days TEXT, created_by_ai BOOLEAN DEFAULT TRUE);
CREATE TABLE messages(id UUID PRIMARY KEY, trip_id UUID, sender_id UUID, message TEXT, sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ratings(id UUID PRIMARY KEY, trip_id UUID, from_user_id UUID, target_user_id UUID, safety INT, on_time INT, communication INT, overall NUMERIC(3,2), comment TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE safety_incidents(id UUID PRIMARY KEY, trip_id UUID, user_id UUID, type TEXT, description TEXT, status TEXT DEFAULT 'open', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
